ci: update node versions
RafaelGSS/nodejs-bench-operations pull request #55
Opened 2023-10-05 02:20 UTC by H4ad

Closes #53

I think we can come up with a rule like this:

- Bench the 3~4 major versions, but only the first and latest versions of each major.
  - Currently, it will add: `18.0.0, 18.18.0, 19.0.0, 19.9.0, 20.0.0, 20.8.0`
- Bench the latest 3 minor versions (except the latest).
  - Currently, it will add: `20.5.0, 20.6.0, 20.7.0`.
- Bench the latest 2 minor versions of LTS (except the latest).
  - Currently, it will add: `18.16.1, 18.17.1`

What do you think?

2023-10-06 09:50 UTC, Fdawgs commented
Probably still want 16 for regression checks though, right?

2023-10-06 11:47 UTC, H4ad commented
After #54 run, we will have the files stored in the git, so we can run the regression checker on those versions and then after this PR, in new benchmarks, we will only have a regression checker for newer versions.

2023-10-07 01:29 UTC, RafaelGSS requested changes

2023-10-10 11:34 UTC, RafaelGSS requested changes
We still need Node.js 16.

2023-10-14 01:14 UTC, RafaelGSS approved these changes

2023-10-14 01:14 UTC, merged